package com.example.masalafoodapplication.util

object Constants {
    const val ARAB = "Arab"
    const val INDIAN = "Indian"
    const val INGREDIENT = "Ingredient"
    const val TIME_MINUTES = "timeMinutes"
    const val DETAILS_KITCHEN = "detailsKitchen"
    const val EXPLORE = "explore"
    const val KITCHENS = "kitchen"
    const val FAV = "fav"
    const val FOOD_DETAILS = "foodDetails"
    const val SUGGESTION_FILTER = "suggestionFilter"
    const val SUGGESTIONS = "suggestions"
    const val QUICK_RECIPES = "QUICK_RECIPES"
    const val FILTER = "filter"
    const val UNKNOWN_HOME_ITEM_TYPE = "Unknown home item type"
    const val TAG_SUGGESTIONS = "SUGGESTIONS"
    const val TAG_HISTORY = "HISTORY"
    const val TAG_KITCHEN_DETAILS = "KITCHEN_DETAILS"
    const val TAG_FOOD_DETAILS = "FOOD_DETAILS"
    const val TAG_SEE_MORE = "QuickRecipesFragment"
    const val KEY_FOOD_ID = "KEY_FOOD_ID"
    const val KEY_CUISINE_NAME = "KEY_CUISINE_NAME"
    const val KEY_SEE_MORE = "KEY_SEE_MORE"
}